export const articles = [
  {
    id: '1',
    type: '研究論文 Research Article',
    title: '從語料庫到語言復振：生成式人工智慧於臺灣客語保存的應用與反思',
    titleEn: 'From Corpus to Revitalization: Generative AI and the Preservation of Taiwan Hakka',
    authors: '張維安・羅惠齡',
    authorsEn: 'Wei-An Chang, Hui-Ling Lo',
    pages: '01–28',
    keywords: ['客語語料庫', '語言復振', '生成式人工智慧', '數位人文'],
    abstract: '本研究探討生成式人工智慧如何運用於臺灣客語語料的整理、標註與知識轉譯，並以四縣腔與海陸腔資料為例，比較人工校訂與模型生成結果。研究顯示，人機協作能擴大語料近用性，但資料治理、腔調差異與文化語境仍需由社群共同把關。',
    abstractEn: 'This study examines how generative artificial intelligence can support the organization, annotation, and interpretation of Taiwan Hakka corpora. Through Siyan and Hailu data, it evaluates human–AI collaboration while foregrounding community governance, dialect variation, and cultural context.',
    doi: '10.69876/jhdh.2026.001',
  },
  {
    id: '2',
    type: '數位方法 Digital Methods',
    title: '客庄文化地景的時空視覺化：苗栗聚落記憶數位典藏實作',
    titleEn: 'Visualizing Hakka Cultural Landscapes: A Digital Archive of Miaoli Communities',
    authors: '彭宏源・劉育誠',
    authorsEn: 'Hung-Yuan Peng, Yu-Cheng Liu',
    pages: '29–62',
    keywords: ['文化地景', 'GIS', '數位典藏', '苗栗客庄'],
    abstract: '本研究整合地方志、歷史地圖與口述訪談，以地理資訊系統呈現苗栗客庄聚落的百年變遷。研究建立可追溯資料來源的時空資料模型，並討論地方記憶在數位化過程中的選擇、缺漏與再脈絡化。',
    abstractEn: 'Integrating gazetteers, historical maps, and oral histories, this study visualizes a century of change in Hakka settlements across Miaoli and proposes a provenance-aware spatiotemporal data model.',
    doi: '10.69876/jhdh.2026.002',
  },
  {
    id: '3',
    type: '研究紀要 Research Note',
    title: '人工智慧生成客語文本的倫理、著作權與文化代表性',
    titleEn: 'Ethics, Copyright, and Cultural Representation in AI-Generated Hakka Texts',
    authors: '林郁珊',
    authorsEn: 'Yu-Shan Lin',
    pages: '63–84',
    keywords: ['人工智慧倫理', '著作權', '文化代表性', '客語'],
    abstract: '本文從客語生成文本案例出發，檢視訓練資料授權、創作者權益、族群刻板印象與錯誤資訊等問題，並提出「來源透明、社群參與、可撤回、可修正」四項治理原則。',
    abstractEn: 'Using Hakka text-generation cases, this note addresses data licensing, creator rights, stereotypes, and misinformation, proposing four principles: provenance transparency, community participation, revocability, and corrigibility.',
    doi: '10.69876/jhdh.2026.003',
  },
  {
    id: '4',
    type: '評論 Review / Comment',
    title: '數位客家研究的公共性：資料、平台與社群之間',
    titleEn: 'The Publicness of Digital Hakka Studies: Data, Platforms, and Communities',
    authors: '鍾國允',
    authorsEn: 'Kuo-Yun Chung',
    pages: '85–102',
    keywords: ['公共人文', '資料治理', '開放取用', '客家研究'],
    abstract: '本文評論近年數位客家研究的資料基礎與公共溝通，主張數位平台除追求技術可用性之外，更應納入社群回饋、長期維護與知識回饋機制。',
    abstractEn: 'This commentary reviews the data foundations and public communication of digital Hakka studies, arguing for community feedback, maintenance, and knowledge reciprocity.',
    doi: '10.69876/jhdh.2026.004',
  },
];

export const issue = {
  volume: '第 1 卷・第 1 期',
  season: '2026 秋季號',
  theme: 'AI 時代的客家知識',
};
